# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: MVVM.WPF - release - nightly build

trigger: none

schedules:
  - cron: "0 0 * * *"
    displayName: MVVM.WPF - release - daily nightly build
    always: false

pool:
  vmImage: 'windows-latest'

steps:

- task: DotNetCoreCLI@2
  displayName: Restore Mvvm.Wpf.csproj
  inputs:
    command: 'restore'
    projects: 'Sources/UI/Mvvm.Wpf/Mvvm.Wpf.csproj'
    feedsToUse: 'select'
    vstsFeed: '38bc0da1-3319-433c-a904-026e89025e23/ee6b9c5d-1dfb-404c-ad78-604066a68c11'

- task: DotNetCoreCLI@2
  displayName: Build Mvvm.Wpf.csproj
  inputs:
    command: 'build'
    projects: 'Sources/UI/Mvvm.Wpf/Mvvm.Wpf.csproj'
    configuration: Debug

- task: DotNetCoreCLI@2
  displayName: Pack Mvvm.Wpf.csproj
  inputs:
    command: 'pack'
    packagesToPack: 'Sources/UI/Mvvm.Wpf/Mvvm.Wpf.csproj'
    nobuild: true
    includesymbols: true

- task: NuGetCommand@2
  displayName: Publish to NuGet.org
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'Nuget.org mateuszokroj1'