# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- Features/*

pool:
  vmImage: 'windows-latest'

steps:

- task: NuGetCommand@2
  displayName: Restore solution
  inputs:
    command: 'restore'
    restoreSolution: $(MVVMSolutionPath)
    feedsToUse: 'select'
    vstsFeed: '38bc0da1-3319-433c-a904-026e89025e23/ee6b9c5d-1dfb-404c-ad78-604066a68c11'

- task: VSBuild@1
  displayName: Build solution
  inputs:
    solution: $(MVVMSolutionPath)
    configuration: 'Debug'
    clean: false
    maximumCpuCount: true